language: generic
os: linux
dist: xenial
install: bash scripts/install-dependencies.sh
before_script: bash scripts/start-services.sh

deploy:
  # deploy develop to the staging environment
  - provider: script
    edge: true
    skip_cleanup: true
    script: bash scripts/deploy.sh sandbox
    on:
      branch: develop
  # deploy master to production
  - provider: script
    edge: true  
    skip_cleanup: true
    script: bash scripts/deploy.sh sandbox
    on:
      branch: master

branches:
  only: 
  - master
  - develop
env:
  global: 
    - CLOUDFOUNDRY_PASSWORD=S220tEq9893Uw44Igsq
    - CLOUDFOUNDRY_USERNAME=joel.stobart@wearesnook.com
    - FRONTEND_PORT=8081
    - FRONTEND_HOST=localhost
    - FRONTEND_PROTO=http
    