language: generic
os: linux
dist: xenial
deploy:
  provider: cloudfoundry
  edge: true
  app_name: Cyber-Health
  api: https://api.london.cloud.service.gov.uk
  username: joel.stobart@wearesnook.com
  organization: mhclg-local-digital
  space: sandbox
  on:
    repo: WeAreSnook/cyber-health-frontend
    branch: develop
  cleanup: false
  password: 'S220tEq9893Uw44Igsq'
branches:
  only:
  - master
  - develop