language: generic
os: linux
dist: xenial
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/deploy.sh sandbox
    skip_cleanup: true
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: bash scripts/deploy.sh production sandbox
    skip_cleanup: true
    on:
      branch: master

branches:
  only: 
  - master
  - develop
env:
  global: 
    - CLOUDFOUNDRY_PASSWORD=S220tEq9893Uw44Igsq
    - CLOUDFOUNDRY_USERNAME=joel.stobart@wearesnook.com